# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.forward_port 8000, 8000

  config.vm.share_folder "openhim-mediator-yeoman-generators", "/openhim-mediator-yeoman-generators", "../"

  config.vm.provision :shell do |shell|
    shell.inline = "mkdir -p /etc/puppet/modules;
                    puppet module install willdurand/nodejs"
  end

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "./"
    puppet.manifest_file  = "yeoman.pp"
  end
end
